//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailClient.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmailDataModelContainer : DbContext
    {
        public EmailDataModelContainer()
            : base("name=EmailDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recipient> RecipientSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<EmailUnit> EmailUnitSet { get; set; }
    }
}
