//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankDataModelContainer : DbContext
    {
        public BankDataModelContainer()
            : base("name=BankDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankBranch> BankBranchSet { get; set; }
        public virtual DbSet<Bank> BankSet { get; set; }
        public virtual DbSet<ExchangeRates> ExchangeRatesSet { get; set; }
        public virtual DbSet<Reviews> ReviewsSet { get; set; }
        public virtual DbSet<ServicesNames> ServicesNamesSet { get; set; }
        public virtual DbSet<Services> ServicesSet { get; set; }
    }
}
