//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        public int Id { get; set; }
        public string Currency { get; set; }
        public decimal Sell { get; set; }
        public decimal Buy { get; set; }
        public int Bank_Id { get; set; }
        public string XmlBankId { get; set; }
    
        public virtual Bank BankSet { get; set; }
    }
}
