//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Id { get; set; }
        public string Sender { get; set; }
        public string ReviewText { get; set; }
        public int Rating { get; set; }
        public int BankBranch_Id { get; set; }
    
        public virtual BankBranch BankBranchSet { get; set; }
    }
}
